"""LabTrust-local mock TraceCertificate (deterministic attach tests only).

Not valid as PCS v0.1 cross-repo release evidence. Use ``release/`` fixtures
generated by CertifyEdge via ``generate_release_candidate.sh``.
"""

from __future__ import annotations

from typing import Any

from labtrust_gym.pcs.deterministic import (
    DETERMINISTIC_CERT_DIGEST,
    DETERMINISTIC_CERT_SOURCE_COMMIT,
    DETERMINISTIC_CERTIFICATE_ID,
)

MOCK_CERTIFICATE_BASENAME = "trace_certificate.mock.v0.json"
CERTIFYEDGE_SOURCE_REPO = "https://github.com/fraware/CertifyEdge"


def build_mock_trace_certificate(receipt: dict[str, Any]) -> dict[str, Any]:
    """Deterministic TraceCertificate-shaped stub for LabTrust unit tests and ``expected/`` goldens."""
    return {
        "certificate_id": DETERMINISTIC_CERTIFICATE_ID,
        "schema_version": "v0",
        "trace_hash": receipt["trace_hash"],
        "spec_hash": receipt["input_hashes"]["workflow"],
        "property_id": "pcs.qc_release.protocol_safety",
        "checker": "certifyedge",
        "checker_version": "0.1.0",
        "status": "CertificateChecked",
        "counterexample_ref": None,
        "created_at": receipt["ended_at"],
        "producer": "certifyedge",
        "producer_version": "0.1.0",
        "source_repo": CERTIFYEDGE_SOURCE_REPO,
        "source_commit": DETERMINISTIC_CERT_SOURCE_COMMIT,
        "signature_or_digest": DETERMINISTIC_CERT_DIGEST,
    }


def is_mock_certificate(cert: dict[str, Any]) -> bool:
    """True when the artifact uses LabTrust fixture digest (not CertifyEdge CLI output)."""
    return cert.get("signature_or_digest") == DETERMINISTIC_CERT_DIGEST
